
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shippingservice
  description: This service is responsible for providing shipping information including pricing and tracking information, when requested from Checkout Service.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/featureflagservice
    - component:default/quoteservice
