
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: recommendationservice
  description: This service is responsible to get a list of recommended products for the user based on existing product IDs the user is browsing.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/featureflagservice
