
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cartservice
  description: This service maintains items placed in the shopping cart by users. It interacts with a Redis caching service for fast access to shopping cart data.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/tree/main/content/en/docs/demo/services/cart
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/featureflagservice
    - resource:default/redis
  providesApis: [pb]