
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffspostgres
  description: This resource is a relational database.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: database
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
