
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend
  description: The frontend is responsible to provide a UI for users, as well as an API leveraged by the UI or other clients. The application is based on Next.JS to provide a React web-based UI and API routes.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/tree/main/content/en/docs/demo/services/frontend
    github.com/project-slug: jmichalak9/opentelemetry-demo
    lighthouse.com/website-url: http://host.docker.internal:8080
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/cartservice
    - component:default/currencyservice
    - component:default/checkoutservice
    - component:default/productcatalogservice
    - component:default/shippingservice
    - component:default/recommendationservice