
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frauddetectionservice
  description: This service analyses incoming orders and detects malicious customers. This is only mocked and received orders are printed out.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/tree/main/content/en/docs/demo/services/frauddetection
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - resource:default/kafka
