
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: This service is responsible to show metrics.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
