
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: loadgenerator
  description: The load generator is based on the Python load testing framework Locust. By default it will simulate users requesting several different routes from the frontend.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/tree/main/content/en/docs/demo/services/loadgenerator
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/frontendproxy
