
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: checkoutservice
  description: This service is responsible to process a checkout order from the user. The checkout service will call many other services in order to process an order.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/tree/main/content/en/docs/demo/services/checkout
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/cartservice
    - component:default/currencyservice
    - component:default/emailservice
    - component:default/paymentservice
    - component:default/productcatalogservice
    - component:default/shippingservice
    - resource:default/kafka
  consumesApis: [pb]