
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: adservice
  description: This service determines appropriate ads to serve to users based on context keys. The ads will be for products available in the store.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
  dependsOn:
    - component:default/featureflagservice
