
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: emailservice
  description: This service will send a confirmation email to the user when an order is placed.
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/jmichalak9/opentelemetry.io/tree/main/content/en/docs/demo/services/email
    github.com/project-slug: jmichalak9/opentelemetry-demo
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: opentelemetry-demo
